### ISSUE TITLE
🐛 Configure command overrides optional parameters even if not specified

### ISSUE THREAD

**Issue by MarcusOtter** [MarcusOtter/discord-needle#114]
### Describe the bug

The `/configure auto-threading` command has optional paremeters, such as `include-bots` and `custom-message` for example. If these options are left out when running `/configure auto-threading`, they will be set to the default value. This is annoying for example if users have set up a long custom message, but then remembers that they need to change another setting. The setting change would remove their custom message, so they have to write the entire command again.

Solution:
Instead of setting them to the default values, set them to the current values (or default if there are no current values).

### Steps to reproduce the bug

1. `/configure auto-threading` `channel: #general` `custom-message: Here's a very long message!\n\nI sure hope I don't have to type this again.`
2. `/configure auto-threading` `channel: #general` `include-bots: true`
3. Send message in #general
4. Thread is not made with `custom-message`, it uses the default one

### Expected behavior

Expected: `custom-message` is used for the auto-thread
Actual: The command on step 2 overwrote the `custom-message` to the default one since it was not provided

**Comment by c43721** [comment]
Sounds like a usecase that modals with selects would fix.

**Comment by MarcusOtter** [comment]
For sure!

**Comment by c43721** [comment]
![image](https://user-images.githubusercontent.com/55610086/179121298-983f1c7b-daf8-4268-8af4-e8e28b464c9a.png)
![image](https://user-images.githubusercontent.com/55610086/179121310-e383b842-d4b0-4db5-9fea-0b15e2cdebf4.png)

By reading the config first then applying null coalescing, we would fix this issue. We can solve that now if we require a quick patch.

Otherwise, wait for modals.
