### ISSUE TITLE
💡 Tagging Threads

### ISSUE THREAD

**Issue by WebDevSimplified** [MarcusOtter/discord-needle#24]
One thing that I think could help people get the correct help quicker would be a way to tag a thread based on a set of categories defined through some command. `/configure categories category:CSS enabled:true`. This tag could then be shown somehow with the thread. For example in the title. The tags could then be generated either automatically from text in the question. For example, if the category is CSS and the question has the word CSS in it then it could autotag it as CSS. The category could also be added by buttons/commands once in the thread similar to how archiving the thread works. This could even be taken a step further and add in the ability to ping specific roles based on the tag given to a thread.

**Comment by MarcusOtter** [comment]
I like this idea, and in fact it's come up before: https://github.com/MarcusOtter/discord-needle/issues/4#issuecomment-911974510

Here are my ideas for the options
- `name` - The name of the tag
- `enabled` - Whether or not the tag should be enabled 
- `autotag?` -  (optional, default `true`) Whether or not the tag should be automatically applied to a thread when an autothreaded message contains it.
- `role?` - (optional, default none) The role that should be pinged when this tag is applied to a thread
- `emoji?` - (optional, default none) The emoji for a tag, that can be used instead of the full tag name to tag the thread. However, I think this only works with emojis that have a utf8 symbol, as threads cannot contain custom emojis in their names (afaik). 

`/configure tags name:CSS enabled:true autotag:true role?:@css-helper emoji?:🎨`

**Comment by MarcusOtter** [comment]
One problem with this is that we do not currently store any information about specific threads - the only thing stored on disk with the bot is the configuration for each server. While we could add something like this to the config file (or another file) it would be nice if this info could still be automatically determined just using discord's API somehow, like structuring the title in a predictable way that always makes the tags be wrapped around parentheses or something.

**Comment by c43721** [comment]
I think I have an idea, based on [highlight discord bot](https://github.com/vladfrangu/highlight):

We can spawn worker threads that test on regex, but to save us a bit of thread spawning issues, we can have some setting called "hasCategories" or whatever. Then, you would configure some text in the configure command and we can use regex or a simple string search algorithm to parse the question before creating the thread.

Not really sure on if this would be fast enough to make it worth it, not mentioning erros that occur during this process. Just thought of this recently and might as well post it here 🙂

**Comment by MarcusOtter** [comment]
I think this is slightly outside of the scope of the projecct right now as we don't store any information about each individual thread on disk. As #72 will be a big problem if we try to store tags in the title, I don't see a good way of implementing this right now. We can maybe revisit this if Discord lowers their rate limit for renaming threads.

**Comment by MarcusOtter** [comment]
As a sidenote this is technically possible with #250 but it's slightly wonky. Basically you can set the custom title to some clever tag regex to match all the tags you want and put it in the title. As you can see my regex skills aren't great so I couldn't figure out a nice way to only match the first time the word occurs (so we get duplicate react here). Also the character casing will be the same way they wrote it.

![image](https://user-images.githubusercontent.com/35617441/187532560-262838af-ef21-4c33-b9aa-794ee0bdad97.png)
![image](https://user-images.githubusercontent.com/35617441/187532634-739523e5-ad68-4be5-b84b-401df4e72e08.png)
