### ISSUE TITLE
💡 Customize default title for auto-threads

### ISSUE THREAD

**Issue by MarcusOtter** [MarcusOtter/discord-needle#29]
**Is your request for improvement related to a problem? Please describe.**
From MumbleMarvin#2812 on Discord:
> Only thing that would be cool if there were customize options for the autocreate thread titles. 
Like "use message", "use image name", "use link title" or stuff like this

Right now the default title for a thread is `Username (yyyy-MM-dd)`. As Marvin points out, it would be nice if this was customizeable.

**Describe the solution you'd like**

Title options (?):
- Name (yyyy-MM-dd)
- First X characters of message
- First line of message
- Use image alt text (if possible? also, what's the fallback if no image here)
- Use link title (sounds like we need to do a HTTP request and like scrape the title but I could be wrong. also, what's the fallback?)

Perhaps the default can be `Name (yyyy-MM-dd)` but if an image or link exists, override it? Though that has problems if someone links to, say, documentation for some programming thing as a source for their question, you wouldn't want that to override. Needs some thinking about.

Solutions: 
- Option A
  When creating a thread, add another optional parameter for the default thread title, where you are given different options.
  Something like `/configure autothreading` `channel: #general` `default-title: First X characters of message` 

- Option B
  A new command like `/configure default-title` `value: First X characters of message` which would set the default for all auto-threads.

**Additional context**
Leaning towards Option A because it's not an extra command, and it would be configurable on a per-channel basis.
Would like feedback on the different title options!

**Comment by Madis0** [comment]
I think you could do all of those variants with variables? Similar to the way default messages have `$USER`.

- `$DATE(format)` - date in the user-specified format, e.g. `$DATE(yyyy-MM-dd)`
- `$FIRSTCHARS(count)` - first X characters of the message
- `$LINKTITLE(count)` - image alt text OR link title OR image filename OR link url OR first X characters of the message
- `$LINKURL(count)` - image filename OR link url OR first X characters of the message

**Comment by MarcusOtter** [comment]
While it would be nice for programmers I worry about the general public having to look up the available variables/options and entering free text. Would be nice to get some sort of dropdown list for this imo, even if it limits customization slightly.

**Comment by Madis0** [comment]
How about this?
/configure autothreading channel:#channel default-title type:user-date value:$user (yyyy-MM-dd)
/configure default-title type:first-characters value:10

Types:

- user-date
- first-characters
- link-title
- link-url

`value` would depend on the type and be optional.

**Comment by ririko5834** [comment]
Good idea

**Comment by runloop** [comment]
After having used Needle on my server this feature is definitely something that would beneficial. Particularly as I am using it auto-thread posts made by a bot. In my instance Link Title is definitely the most important option. I'm not sure I see the value in Link URL.

First characters is also a good option. Though a more suitable name would be `prefix`.

**Comment by maddie-wang** [comment]
My members want a user friendly title too! I want to use first line of message :)

Will use it ASAP when its released. Need it!

<img width="849" alt="image" src="https://user-images.githubusercontent.com/32725368/160923504-d9e9d1be-093b-4052-80de-7d16e99ee4be.png">

**Comment by averon420** [comment]
push - would love that

**Comment by distantnative** [comment]
That would be so great!

**Comment by Snailedlt** [comment]
Not sure if this falls under this issue, or if I should make s new one, so here goes.

It would be nice if we could customize the first message sent by needle after a thread is created.

We can sort of do this already. That is we can customize the text, but not the buttons below it.

It would be nice if we could also customize the buttons below.

See this for example:
![Screenshot_20220614_171042.jpg](https://user-images.githubusercontent.com/43886029/173615061-70250f65-4b3d-4d6b-9f3f-a63fcb0e1350.jpg)

If it was possible to customize buttons here, we could add a button for changing the title, instead of asking the user to change the title through the message.

Another option would be to prompt the user straight away for what they want the thread title to be, and then the first message they type after that prompt is set to the title. Then when they have written a title, the bot can respond with a message saying that they can change the title with the `/title` command.


Anyways, let me know if I should make a new issue for this, or if it fits under this one

**Comment by Snailedlt** [comment]
> How about this?
> `/configure autothreading channel:#channel default-title type:user-date value:$user (yyyy-MM-dd)` for specific
> `/configure default-title type:first-characters value:10` for global
> 
> Types:
> 
> - user-date
> - first-characters
> - link-title
> - link-url
> 
> `value` would depend on the type and be optional.

I very much like this idea!

It works well both for customization and simplicity.

**Comment by MarcusOtter** [comment]
@Snailedlt 
Button customization goes under issue #31 

>we could add a button for changing the title

This is the plan :)

> Another option would be to prompt the user straight away for what they want the thread title to be, and then the first message they type after that prompt is set to the title.

I don't really like this UX, and Discord wants basically all intreactions to be through commands (not when users write messages, etc)

I do have a plan for implementing this. I just need to find the time...
I started working on something in PR #155 which is promising. It basically looks like this.

![image](https://user-images.githubusercontent.com/35617441/173617579-3d7cd03d-a4e4-49ad-a8a7-268c8eaf1e22.png)

**Comment by Snailedlt** [comment]
@MarcusOtter ohh yes!
That modal feature would be great for titles . Especially if it can be opened by buttons

**Comment by MarcusOtter** [comment]
Update on this: I added support for [RegEx](https://en.wikipedia.org/wiki/Regular_expression), message variables, and a custom max title length. Will be out with the next update (along with a LOT of other changes). Example of the feature:

![image](https://user-images.githubusercontent.com/35617441/186522040-572534df-cd32-4942-bd17-24bbe3935b31.png)
![image](https://user-images.githubusercontent.com/35617441/186522137-b47aef0a-75dc-4d26-b902-22e2b8eb2005.png)

**Comment by DooNotResuscitate** [comment]
How would this feature respond to the message being a modal? For example I'm thinking of using needle to auto create threads on my [sesh.fyi ](https://sesh.fyi/)posts. @MarcusOtter

**Comment by MarcusOtter** [comment]
Excellent question @DooNotResuscitate, I had not tested it. Right now it doesn't work!

How do you suggest I implement support for this? My initial idea is to just append all embeds (title + description + fields + footer) for every embed. It might look messy but we can't really assume that an embed will always have the most important content in the description or in the fields, I think.

**Comment by DooNotResuscitate** [comment]
> Excellent question @DooNotResuscitate, I had not tested it. Right now it doesn't work!
> 
> How do you suggest I implement support for this? My initial idea is to just append all embeds (title + description + fields + footer) for every embed. It might look messy but we can't really assume that an embed will always have the most important content in the description or in the fields, I think.

My personal suggestion would be to just pull the value from the title field - the Apollo bot (which has built-in thread creation) just uses the embed title for the thread title. It also includes the event time, but that's because it knows what date exactly to pull.

![Screen Shot 2022-08-29 at 19 40 06](https://user-images.githubusercontent.com/33287665/187317388-efca80fc-f11b-4ecf-941e-73e13d37bebc.png)

![Screen Shot 2022-08-29 at 19 40 28](https://user-images.githubusercontent.com/33287665/187317391-f42e9e41-2410-4641-96f0-378a87bc3555.png)

So for my purposes I would be content with just the embed title being pulled, but I'm wondering how it would be listed as an option like the others above. Maybe a separate parameter would need to be added for embeds specifically? Something like the already existing "title-format" and also "title-format-embed"? That way you could give a couple options specifically for if an embed is detected like: Title, Description, Title + Description, etc. @MarcusOtter

**Comment by MarcusOtter** [comment]
This is not something I would make configurable, we should just pick a reasonable default to keep the amount of unnecessary options down. Since you will be able to regex on this anyways, I think I'll just do (title + \n\n + description + \n\n + field title + \n + field description + \n\n + footer) and then if you know you only want the title you can just target that with a regex.

The message content for the embed you showed would be
> <@&XXXXXXXXXXXXXXXXXX>
> 
> DURF Weekly Game
> 
> Requirements: 18+, good mic and solid internet connection.
> Players: 3-5 total
> ...
>
> Time
> <t:1662296400:F> - <t:1662307200:t>
> ....

**Comment by DooNotResuscitate** [comment]
Yeah if the returned output can be regexed, then I think your default is just fine.

**Comment by DooNotResuscitate** [comment]
So with this implemented, would the plain default with no `title-format` option be the above if an embed is detected?

**Comment by MarcusOtter** [comment]
The default would be the first 50 characters of the message, where the message in this case is the message content + embeds content.

**Comment by DooNotResuscitate** [comment]
Got it - so in the case of the message being just the embed by itself, would be first 50 chars of the embed. That works, and I assume the regex will parse over the whole entire message so I could pull whatever part out?

**Comment by MarcusOtter** [comment]
Yep!
