### ISSUE TITLE
💡 Improvement: Purge configuration data of removed guilds

### ISSUE THREAD

**Issue by nchristopher** [MarcusOtter/discord-needle#36]
**Is your request for improvement related to a problem? Please describe.**
Needle doesn't delete configuration data of guilds where Needle has been removed.

While individual guild configuration is relatively small, it could add up if Needle scales to many guilds in the future. Additionally, Discord's [Developer Policy](https://discord.com/developers/docs/policy#handle-data-with-care) states that you may not "retain data any longer than necessary for the operation of your application." 

**Describe the solution you'd like**
Upon receiving the [`guildDelete`](https://discord.js.org/#/docs/main/stable/class/Client?scrollTo=e-guildDelete) event, Needle should delete the corresponding file from the config directory.

Because a guild could be removed when Needle is offline, the bot should query the files in the config directory & compare it against current guilds, deleting unused ones.

**Comment by MarcusOtter** [comment]
This is a fantastic suggestion! Happy to get working on this ASAP (which may be in a week or so unfortunately). Thank you!

**Comment by c43721** [comment]
FYI You aren't required to remove data you don't need as long as your privacy policy states this fact. I made a suggestion for the privacy policy anyways as it's a requirement for verification. The argument to be made is that the entire lifetime of the bot considers configuration as "essential information" but that's not what I'm here to discuss.

But I also +1 this, since having the least amount of files is always a good thing. But we should note this just in case someone hollars "why did my configuration die 😠😠😠"
