### ISSUE TITLE
Add an auto thread option for everyone but the OP when used in the forums

### ISSUE THREAD

**Issue by pbandjib** [MarcusOtter/discord-needle#387]
### Describe the improvement

Allow the auto threading for all users BUT the OP of their own forum post.

### Problems this improvement solves

Discord's forum system only works in a broad sense. But, if you want to have forums based around tracking someone's progress (Ex: build post, DIY post, progress post, etc) it will get cluttered with other peoples messages fairly quickly.

By allowing auto threading in a forum for everyone but the OP, it would allow the OP to continue to post updates, but keep the questions and side conversations that other people start, into threads in the forums post.

I am not sure if this is even possible, but if it is, it would open a ton of possibilities for forums

### Alternative solutions

Currently none that I can find.

**Comment by pbandjib** [comment]
Currently none that I can find

**Comment by MarcusOtter** [comment]
Hi @pbandjib, sorry for the late reply. If I understand you correctly, this feature request is about creating threads inside a forum post? This is unfortunately not possible in Discord, as Threads can only be created inside normal text channels.

**Comment by MarcusOtter** [comment]
I understand this issue as "create threads inside forum posts" which is not possible since forum posts are actually basically threads under the hood. You can see this in your client as well in GitHub, that you do not get the option to create a thread inside forums. 

If I misunderstood the feature request let me know and I can re-open!
