### ISSUE TITLE
💡 Add emojis to each thread starting message

### ISSUE THREAD

**Issue by ZibratR** [MarcusOtter/discord-needle#396]
### Describe the improvement

Option to automatically add certain emojis to the initial message that a thread is created off of.

### Problems this improvement solves

As an example, this would be helpful in a feedback / suggestion channel where ideas can be voted on.

**Comment by MarcusOtter** [comment]
@ZibratR Thanks for the suggestion. One key design goal of Needle is to keep it as a simple, single-purpose bot and not add features that are unrelated to the core functionality (which is automatically creating threads). This is so we can focus on one thing and do that one thing well instead of being a jack of all trades. 

In my mind something like this would be great for another single purpose bot - a bot that simply adds certain reactions to every new message in a channel. There may be bots like that out there! But unfortunately it's out of scope for Needle.
