### ISSUE TITLE
💡 Improvement: Bot ToS and Privacy Policy

### ISSUE THREAD

**Issue by c43721** [MarcusOtter/discord-needle#40]
Discord requires a Privacy Policy and ToS for all verified bots going forward.

![image](https://user-images.githubusercontent.com/55610086/151099429-94c35382-1092-4470-8d41-4a202929fee9.png)

Should add a ToS and Privacy Policy, which can mention that we store data like with https://github.com/MarcusOtter/discord-needle/pull/39.

**Comment by MarcusOtter** [comment]
Makes sense to me, I was looking at adding this before but I'm not exactly a lawyer. But **I think** a privacy policy is only needed if we handle any personal data, and since we do not track/store any messages or really anything that can be traced back to users, I don't think it's strictly necessary (though I would still like one).

I'll also point out that Needle does not need to be verified because none of Discords privileged intents are checked (we are not collecting any data)

![image](https://user-images.githubusercontent.com/35617441/151183127-2a816a41-0c9d-4b6f-b12c-3696cf6cd69b.png)

**Comment by MarcusOtter** [comment]
It would be good to see what privacy policy & terms of service other bots have to take inspiration from them. I want a restrictive privacy policy that basically says that we are not allowed to collect any data except for what's absolutely necessary (guild config)

**Comment by c43721** [comment]
>  But I think a privacy policy is only needed if we handle any personal data
Incorrect, Discord now requires all bots moving forward regardless of handling personal data or not. 

I need to write my ToS for Payload (since I was from a time before this new age 😁) so I can probably help scaffold something in the future. I think I have some good layouts that might help.

**Comment by MarcusOtter** [comment]
> Incorrect, Discord now requires all bots moving forward regardless of handling personal data or not.

In the image you sent, they say "when applying for verification", which I don't have an intention of doing unless I really need to. So Discord doesn't seem to be enforcing it. And GDPR enforces it if we handle personal data, which we do not.

**Comment by MarcusOtter** [comment]
One privacy policy I really like is https://darkreader.org/privacy/ which should (with some modification to deal with Discord bots instead of browser extensions) apply to us as well:

> Dark Reader had never collected and will never collect any personal data, browsing history etc.

> In future Dark Reader may collect browser version, platform name, display settings and user's filter settings (except website list or any other data which can help identify user). This information is needed for decision on implementing new features, removing unused features or suggesting default settings for new users. It will happen only with your permission. 

The "it will happen only with your permission" is key, we should follow privacy by default and have any data collection features behind a command you need to invoke manually to enable said feature :)

**Comment by c43721** [comment]
> In the image you sent, they say "when applying for verification"

So as long as you're not planning to be in more than 76 servers 😉

That snippet you sent is great. I think that's more than enough if we modify it slighly (the good old copy paste)

**Comment by MarcusOtter** [comment]
> 76 servers 

Oh, do bots need to be verified even if they don't have any privileged intents? We will probably hit 76 some time next week at this rate 😅

**Comment by c43721** [comment]
Yup, all bots need to be verified I think when they hit 76 servers. There was a max of 100 when unverified, but I don't remember if this changed or not. 

Sorry to break it to you now 😀

**Comment by MarcusOtter** [comment]
Good to be prepared, thanks for letting me know 🚀

**Comment by MarcusOtter** [comment]
Just got the notification exactly 1 week after I said next week 😎 

Anyways, do you think the "TOS" in the license is enough?

**Comment by c43721** [comment]
Likely, but it does not explain to users their rights or our rights operating the bot.

I would take some inspiration from other bots.

**Comment by MarcusOtter** [comment]
> does not explain to users their rights or our rights operating the bot

I think it does:

> 15. Disclaimer of Warranty.
  THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY
APPLICABLE LAW.  EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT
HOLDERS AND/OR OTHER PARTIES PROVIDE THE PROGRAM "AS IS" WITHOUT WARRANTY
OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO,
THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE.  THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE PROGRAM
IS WITH YOU.  SHOULD THE PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF
ALL NECESSARY SERVICING, REPAIR OR CORRECTION.

> 16. Limitation of Liability.
  IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING
WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MODIFIES AND/OR CONVEYS
THE PROGRAM AS PERMITTED ABOVE, BE LIABLE TO YOU FOR DAMAGES, INCLUDING ANY
GENERAL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE
USE OR INABILITY TO USE THE PROGRAM (INCLUDING BUT NOT LIMITED TO LOSS OF
DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR THIRD
PARTIES OR A FAILURE OF THE PROGRAM TO OPERATE WITH ANY OTHER PROGRAMS),
EVEN IF SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF
SUCH DAMAGES.

> 17. Interpretation of Sections 15 and 16.
  If the disclaimer of warranty and limitation of liability provided
above cannot be given local legal effect according to their terms,
reviewing courts shall apply local law that most closely approximates
an absolute waiver of all civil liability in connection with the
Program, unless a warranty or assumption of liability accompanies a
copy of the Program in return for a fee.

**Comment by MarcusOtter** [comment]
Created first version of the privacy policy [here](https://github.com/MarcusOtter/discord-needle/blob/various-fixes/PRIVACY_POLICY.md), feel free to review.
