### ISSUE TITLE
💡 Improvement: Max non archived Thread per user

### ISSUE THREAD

**Issue by Salvi0** [MarcusOtter/discord-needle#41]
**Is your request for improvement related to a problem? Please describe.**
Usually users can mass create threads in a autothreading channel. This somehow cause a mess in the threads list.

**Describe the solution you'd like**
Simply a way to let the staff of a server to set a maximum cap of open threads per users for every autothreading channels in their server. The default value for such option should be infinite. This will help a lot with the general management of threads and completely removing the above problem.

**Describe alternatives you've considered**
Just living with the current settings and adapt to them.

**Comment by MarcusOtter** [comment]
Agreed that it can get pretty spammy in some thread channels! Does Discord's native slowmode feature do anything for you regarding this issue? I usually set it to about 10 minutes which prevents users from mass-creating threads

![image](https://user-images.githubusercontent.com/35617441/151704335-2b3f55c7-9883-43b3-84c3-c09c2acf3d69.png)

Some other servers that use Needle put it on 6 hours because they only want one thread per user per day, pretty much. Perhaps that could be a better solution than the proposed solution?

**Comment by Salvi0** [comment]
Yea it helped me a lot using the slow mode. Personally I don't have any other intuitive solution at the moment, but the one I suggested above. Even tho I repeat that the slowmode is fine and it will just be more idk attractive or sexy to also have away to cap threads!!.

**Comment by MarcusOtter** [comment]
Gotcha! I think I want to keep the features to a minimum to not bloat the slash command context in Discord and also to keep the complexity of the bot down. I'm thinking we could possibly do this in the future, but I don't see a clear use case for it right now that is not solved by slow mode. I get that it can feel more attractive if the bot has its own cool custom features, but it also feels like re-inventing the wheel a bit here. Also, it would be a relatively big feature to implement as we do not currently track how many threads are opened (and by which user) and I'm hoping to making it stay that way.

**Comment by Salvi0** [comment]
Alright got it. I look forward for a major update ^-^

**Comment by ririko5834** [comment]
Ok but you can't limit that user will have just max 1 thread in 2 days with slowmode
