### ISSUE TITLE
💡 Add delete thread command

### ISSUE THREAD

**Issue by ririko5834** [MarcusOtter/discord-needle#43]
Add slash command to delete thread for staff.

**Comment by MarcusOtter** [comment]
I could do this but I'm worried if we go overboard with slash commands the UI will be cluttered and hide the commands that will be used often. Is there a reason for not using the delete button?
![image](https://user-images.githubusercontent.com/35617441/151812233-fac8576a-8b98-4017-9b18-f2dd4cc4c624.png)

**Comment by ririko5834** [comment]
Staff prefers commands. Maybe there should be a Delete button sent as the archive thread button is sent with the first message. This button should work only for staff with manage threads perms. It should send an error message when the user cant close the thread.

**Comment by MarcusOtter** [comment]
I do like that! I really wish there was a way to only show buttons to people that had access to them, then we could've gone wild with buttons for staff without users being confused by all the options. Perhaps if a user click it, it will archive instead of delete. Also, I might wait with this until we get a confirmation button as detailed in #32 since that's what Discord does as well


![image](https://user-images.githubusercontent.com/35617441/151816137-a3e45602-9daa-4b47-856a-fbe32b0de129.png)

**Comment by c43721** [comment]
> I really wish there was a way to only show buttons to people that had access to them, then we could've gone wild with buttons for staff without users being confused by all the options

This won't happen as Discord prefers to keep buttons stateless. Your suggestion does poke some double-useage, but I can see a moderator wanting to archive and accidently deleting. 

IMO this should not be a command and should be kept to the native UI, otherwise we're rewriting what Discord did already. 

For your pop-up confirmations, I don't think that's in the Q1/Q2 roadmap for Discord. Modals are going to be in closed beta today I think, which is slated for a release pending another one of their changes (I think andriod is getting a rewrite? something's going on at least). The only modal component is Text, and I could see them writing a confirm component in the future. This might want to wait until that is announced or there is a workaround.

**Comment by MarcusOtter** [comment]
> IMO this should not be a command and should be kept to the native UI, otherwise we're rewriting what Discord did already.

This was my initial concern as well. I'll think a bit about this but it's pretty far down on my priority list right now.

**Comment by MarcusOtter** [comment]
I don't see this being added right now, but I'll mark it as "maybe later" so we can revisit it in the future. One big goal for me is to keep the complexity down in this project, and re-implementing discord's features is not on top of my list of features that I want to add. Sorry!

**Comment by ririko5834** [comment]
:/

**Comment by ririko5834** [comment]
Oh
