### ISSUE TITLE
💡 Add member to thread on reaction

### ISSUE THREAD

**Issue by tylothedino** [MarcusOtter/discord-needle#452]
### Describe the improvement

A way for the bot to create a role specifically for that thread and only those that react to the creation message can see the thread and not spam others who don't need to see the information. 

The use of this to be more specific, is let's say that the group in the discord is trying to organize an event and let's say someone says, "Taylor Swift Concert 9/21" and that message generates a thread but no one gets added to the thread other than the person who wrote the message. Then those that want to be a part of the event reacts to the message and gets added to the thread and now everyone can converse in that thread.

**Comment by MarcusOtter** [comment]
@tylothedino It is already possible for users to join a thread with Discord's interface by right clicking the thread and selecting "Join Thread". Adding a role to a user does not hide or show threads automatically, because public threads cannot be shown/hidden individually with permissions. Can you elaborate on why Discord's UI cannot be used for this?

**Comment by MarcusOtter** [comment]
Closing because lack of a reply, happy to re-open if it is clarified further
