### ISSUE TITLE
💡 Support tickets panel

### ISSUE THREAD

**Issue by ririko5834** [MarcusOtter/discord-needle#48]
**Describe the feature you'd like**
Add command to make embed with button in some channel, then when users click on the button, a thread will be created for them. It could be good for support tickets system.
Allow one user to have just one supportthread open at the time, threads should be named in `username-usertag` or `userid` format.

When a thread is opened by the bot, add there the user send message with button to close it. Then when staff clicks on this button, thread should be archived (locked). Also owner of the thread (user) should be able to close it. when it's resolved.

Maybe there should be also option to add some pre-made questions (FAQ) that users can pick a question from menu or open a ticket.

Example:
![image](https://user-images.githubusercontent.com/64729293/150481466-50ab68e1-47fe-4fb5-a6d0-016be1d4f6ff.png)

Its from suggester support server - https://suggester.js.org/support

**Comment by c43721** [comment]
this might be a bit outside of the scope for needle, though. Also, this requires private threads in the target discord to work properly, otherwise you must create/manage channels (which has been done a million times).

this would also be much better suited for the upcoming modal component, <https://devsnek.notion.site/Modal-aka-Form-Interactions-e839b3dd8c214eb08f950764a8328e36> as it would fast forward the question asking start of any support ticket thread system.

**Comment by ririko5834** [comment]
Ok
private threads are not needed, this can be for public support as on suggester support server it is.

**Comment by MarcusOtter** [comment]
One problem with support desks imo is that threads are not discoverable (since they do not show up in the channel list unless you are in the thread), which is why I prefer creating a thread on every message since you can see in that channel what threads are active more easily. It's a good suggestion but slightly out of scope right now. Can revisit in future.
