### ISSUE TITLE
Feature Request: let the original author close the thread

### ISSUE THREAD

**Issue by FredKSchott** [MarcusOtter/discord-needle#6]
It would be great if the original author could close the thread with a "Thank you!" or "Close thread" message. We could show instructions on how to do this in our fist message that the bot posts in the thread.

**Comment by MarcusOtter** [comment]
Definitely! If users create threads manually DIscord lets them do this by default, as well as changing the title of the thread. It'd be really nice if the bot could transfer the ownership of the thread but I don't think that's possible... Perhaps just adding commands for it will be a good enough workaround. It's either that or giving the user instructions on how to create a thread from the message manually I think.

**Comment by natemoo-re** [comment]
The first message could automatically add some emojis and when the original author reacts with one of the emojis, an action is triggered? It would be similar to the [MEE6](https://mee6.xyz/) automatic role assignment.

**Comment by MarcusOtter** [comment]
Good idea @natemoo-re, perhaps we could use buttons for this instead since it would be more obvious for the user and also better when it comes to ratelimiting (we don't have to listen to every reaction in every server the bot is in).

Perhaps one button for changing the name of the thread (a la https://github.com/MarcusOtter/discord-auto-threader/issues/4), one destructive red button for archiving it, and one button to bump it (a la https://github.com/MarcusOtter/discord-auto-threader/issues/7)

Would like to start looking at these fantastic feature requests some time next week!

https://support.discord.com/hc/en-us/articles/1500012250861-Bots-Buttons
![image](https://user-images.githubusercontent.com/35617441/131896214-725aac2d-c4d1-4596-85c2-48126a49ebfa.png)

**Comment by MarcusOtter** [comment]
Fixed with #15 (also available as a command, `/close`)

![image](https://user-images.githubusercontent.com/35617441/134777648-c044ec92-0691-45c6-a5a4-15799f68671c.png)
